services:
  mongo:
    restart: unless-stopped
    image: mongo:latest
    command:
      - --storageEngine=wiredTiger
    logging:
      driver: none

    volumes:
      - ba-mongo:/data/db
    ports:
      - '37001:27017'

  # postgres:
  #   image: postgres:16
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: postgres
  #     # PGDATA: /var/lib/postgresql/data
  #   volumes:
  #      - ba-postgres:/var/lib/postgresql/data
  #   ports:
  #     - "37002:5432"
  #   restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    restart: unless-stopped
    volumes:
      - ba-mailpit:/data
    ports:
      - 38025:8025
      - 11025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  ba-mongo:
  # ba-postgres:
  ba-mailpit:
