import { normalTestSuite } from '@better-auth/test-utils/adapter'
import { describeAdapterSuite } from './adapter.harness.js'

describeAdapterSuite({
  name: 'Payload Adapter Tests (normal)',
  idType: 'uuid',
  tests: [
    normalTestSuite({
      disableTests: {
        // carried over from the previous harness (runAdapterTest):
        // SHOULD_FIND_MANY_WITH_NOT_IN_OPERATOR
        'findMany - should find many models with not_in operator': true,
        // SHOULD_PREFER_GENERATE_ID_IF_PROVIDED
        'create - should use generateId if provided': true,
        // deliberate design decision: ids are generated by payloadcms (the
        // db owns id generation; disableIdGeneration strips provided ids).
        // The test asserts the provided-id roundtrip — provided-id/custom-ID
        // support is deferred to after the upgrade plan is complete
        'create - should create a model': true,
      },
    }),
  ],
})
