import { joinsTestSuite } from '@better-auth/test-utils/adapter'
import { describeAdapterSuite } from './adapter.harness.js'

describeAdapterSuite({
  name: 'Payload Adapter Tests (joins)',
  idType: 'uuid',
  tests: [
    joinsTestSuite({
      disableTests: {
        // deliberate design decision: ids are generated by payloadcms (the
        // db owns id generation; disableIdGeneration strips provided ids).
        // The test asserts the provided-id roundtrip — provided-id/custom-ID
        // support is deferred to after the upgrade plan is complete
        'create - should create a model': true,
      },
    }),
  ],
})
