import type { CollectionConfig } from 'payload'
// Account
// createdAt and updatedAt are autogenerated by Payload CMS
export const accountCollection: CollectionConfig = {
  slug: 'account',
  fields: [
    {
      name: 'userId',
      type: 'text',
    },
    {
      name: 'accountId',
      type: 'text',
    },
    {
      name: 'providerId',
      type: 'checkbox',
    },
    {
      name: 'accessToken',
      type: 'checkbox',
    },
    {
      name: 'refreshToken',
      type: 'checkbox',
    },
    {
      name: 'accessTokenExpiresAt',
      type: 'date',
    },
    {
      name: 'refreshTokenExpiresAt',
      type: 'date',
    },
    {
      name: 'scope',
      type: 'text',
    },
    {
      name: 'idToken',
      type: 'text',
    },
    {
      name: 'password',
      type: 'text',
      hidden: true,
    },
  ],
}
