import type { CollectionConfig } from 'payload'
// Session
// createdAt and updatedAt are autogenerated by Payload CMS
export const sessionCollection: CollectionConfig = {
  slug: 'session',
  fields: [
    {
      name: 'userId',
      type: 'text',
    },
    {
      name: 'token',
      type: 'text',
    },
    {
      name: 'expiresAt',
      type: 'date',
    },
    {
      name: 'ipAddress',
      type: 'text',
    },
    {
      name: 'userAgent',
      type: 'text',
    },
  ],
}
