import type { CollectionConfig } from 'payload'

// User
// createdAt and updatedAt are autogenerated by Payload CMS
export const userCollection: CollectionConfig = {
  slug: 'user',
  auth: true,
  fields: [
    {
      name: 'name',
      type: 'text',
    },
    {
      name: 'email',
      type: 'text',
    },
    {
      name: 'emailVerified',
      type: 'checkbox',
      // hidden: true,
    },
    {
      name: 'image',
      type: 'text',
    },
  ],
}
