import type { CollectionConfig } from 'payload'
// Verification
// createdAt and updatedAt are autogenerated by Payload CMS
export const verificationCollection: CollectionConfig = {
  slug: 'verification',
  fields: [
    {
      name: 'identifier',
      type: 'text',
    },
    {
      name: 'value',
      type: 'text',
    },
    {
      name: 'expiresAt',
      type: 'date',
    },
  ],
}
